### ISSUE TITLE
Print summary as plain text

### ISSUE THREAD

**Issue by moos** [AndrewTBurks/json-summary#7]
I would like to be able to print the summary as plain text, usable say in the terminal:
```
{
  WN: {
    SYNSET: (117658) [
      {
        ILR: 40.0% <string>,
        ID: 100% <string>,
        SYNONYM: 100% {
          LITERAL: 80.0% <string>
        },
        DEF: 100% <string>,
        USAGE: 10.0% (2) [<string>],
        POS: 100% <string>
      }
    ]
  }
}
```
Thoughts or open to PR?

**Comment by AndrewTBurks** [comment]
@moos the percentages (e.g. 80% <string>) are the occurrence % correct? It shouldn't be too complicated. I'll play around with it

**Comment by AndrewTBurks** [comment]
json-summary now has support for plaintext output from #8 in v1.2.0

Feel free to reopen or open a new issue with any problems/feedback!

**Comment by moos** [comment]
Great -- thanks for the quick response and update.
